Repository canonical/multipass.run, pull requests merged in 2019-05, with the labels that each got.

#24 Add the official logo and favicon
  .docker-project
  _includes/footer.html
  _includes/head.html
  _includes/navigation.html
  _sass/_settings_colors.scss
  index.html
  install.html
  js/modules/global-nav/index.js
  js/tabs.js
  package.json
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#25 Update repo name
  _includes/footer.html
  package.json
Labels: Review: Code +1

#30 Add snapcraft badge on install page
  install.html
Labels: Review: Code +1, Review: QA +1

#29 Fix typo on the install page
  install.html
Labels: Review: Code +1

#31 Add GA/GTM with the proper config for Optimize
  _layouts/default.html
Labels: Review: Code +1, Review: QA +1

#33 Update homepage and remove install page
  Gemfile
  Gemfile.lock
  _config.yml
  _includes/footer.html
  _includes/navigation.html
  _sass/_pattern_card.scss
  _sass/_utilities_grid.scss
  _sass/main.scss
  index.html
  install.html
  js/installversion.js
  js/mediabox.js
  js/osselector.js
  js/tabs.js
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#36 Skip the prerelease releases when generating the download link
  index.html
  js/installversion.js
Labels: Review: Code +1, Review: QA +1
