Repository canonical/multipass.run, pull requests merged in 2019-12, with the labels that each got.

#57 Remove useless redirect
  nginx.conf
Labels: Review: Code +1, Review: QA +1

#63 Name the flask project, for the logs
  webapp/app.py
Labels: Review: Code +1

#62 Create update.yaml and .json
  update.json
  update.yaml
Labels: Review: Code +1

#64 Set up /static/latest-release.json
  static/latest-release.json
  update.json
  update.yaml
  webapp/app.py
Labels: Review: Code needed, Review: QA needed

#66 Add Discourse module
  .docker-project
  entrypoint
  requirements.txt
  static/sass/_layout-documentation.scss
  static/sass/main.scss
  templates/_layouts/default.html
  templates/docs/_base_docs.html
  templates/docs/document.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#70 Update latest-release.json for 1.0
  static/latest-release.json
Labels: Review: Code +1

#69 Replace foo and bar
  templates/index.html
Labels: Review: Code +1

#68 Update docs link down the page
  templates/index.html
Labels: Review: Code +1
